stages:
  data_preprocessing:
    desc: "Create complete vocabulary for training the Autoembedder"
    cmd:
    - python scripts/preprocess_data.py
    params:
    - data_preprocessing
    deps:
    - scripts/preprocess_data.py
    - utils/feature_handler.py
    - utils/params.py
    - ./feature_handling/feature_actions.json
    outs:
    - data/training_input/
    - feature_handling/feature_handler.json
    - feature_handling/feature_handler_pretty_summary.json
  train_autoembedder:
    desc: "Train the AutoEmbedding model and save to disk."
    cmd:
    - python scripts/train_autoembedder.py ./data/training_input/
    params:
    - train_autoembedder
    deps:
    - scripts/train_autoembedder.py
    - ./feature_handling/feature_handler.json
    - ./utils/feature_handler.py
    - ./data/training_input/
    - ./autoembedder/
    outs:
    - ./data/model/
  test_autoembedder:
    desc: "Test the trained AutoEmbedding model."
    cmd:
    - python scripts/test_autoembedder.py ./data/training_input/ ./data/model/autoembedder
    params:
    - test_model
    deps:
    - scripts/test_autoembedder.py
    - ./data/training_input/
    - ./data/model/
    - ./autoembedder/
  train_supervised_classification_embedding:
    cmd:
    - python scripts/supervised_classification_wembedding.py ./data/training_input/
    params:
    - train_simple_classification_model
    deps:
    - ./data/training_input/
    - ./scripts/supervised_classification_wembedding.py
  train_supervised_classification_autoembedding:
    cmd:
    - python scripts/supervised_classification_wautoembedding.py ./data/training_input/ ./data/model/autoembedder
    params:
    - train_simple_classification_model
    deps:
    - scripts/test_autoembedder.py
    - ./data/training_input/
    - ./data/model/
    - ./autoembedder/