stages:
  data_preprocessing:
    desc: "Create complete vocabulary for training the Autoembedder"
    cmd:
    - python scripts/preprocess_data.py
    params:
    - data_preprocessing
    deps:
    - scripts/preprocess_data.py
    - utils/feature_handler.py
    - utils/params.py
    outs:
    - data/training_input/
    - feature_handling/feature_handler.json
    - feature_handling/feature_handler_pretty_summary.json
  # train:
  #   desc: "Train the AutoEmbedding model and save to disk."
  #   cmd:
  #   - python scripts/train_auto_embedder.py ./train_input/
  #   params:
  #   - train_model
  #   deps:
  #   - scripts/train_auto_embedder.py
  #   - ../feature_handling/feature_handler.json
  #   - ../mldq/feature_handler.py
  #   - ./train_input/
  #   - ./embedding/
  #   - ../mldq/simple_script.py
  #   outs:
  #   - model/
  # test:
  #   desc: "Test the trained AutoEmbedding model."
  #   cmd:
  #   - python scripts/test_auto_embedder.py ./train_input/ ./model/auto_embedder/
  #   params:
  #   - train_model
  #   deps:
  #   - scripts/test_auto_embedder.py
  #   - ./train_input/
  #   - ./model/
  #   - ./embedding/
  #   - ../mldq/simple_script.py
