
# vars:
# - config/penguin_data.yaml
# - config/adult_income_data.yaml

stages:
  data_preprocessing:
    desc: "Create complete vocabulary for training the Autoembedder"
    cmd:
    - python scripts/preprocess_data.py
    params:
    - data_preprocessing
    deps:
    - ./scripts/preprocess_data.py
    - ./utils/feature_handler.py
    - ./utils/params.py
    - ./utils/data.py
    - ./feature_handling/feature_actions_adult_income.json
    - ./feature_handling/feature_actions_penguins.json
    outs:
    - ./data/training_input/
    - ./feature_handling/feature_handler.json
    - feature_handling/feature_handler_pretty_summary.json
  train_autoembedder:
    desc: "Train the AutoEmbedding model and save to disk."
    cmd:
    - python scripts/train_autoembedder.py ./data/training_input/
    params:
    - train_autoembedder
    deps:
    - ./scripts/train_autoembedder.py
    - ./feature_handling/feature_handler.json
    - ./utils/feature_handler.py
    - ./utils/data.py
    - ./utils/visualisation.py
    - ./data/training_input/
    - ./autoembedder/
    outs:
    - ./data/model/
    - ./data/plots_autoembedder/
    - ./data/metrics_autoembedder/
  train_supervised_classification_embedding:
    cmd:
    - python scripts/supervised_classification_wembedding.py ./data/training_input/
    - python scripts/supervised_classification_wembedding.py ./data/training_input/ ./data/model/autoembedder
    params:
    - train_classification_models
    deps:
    - ./data/model/
    - ./data/training_input/
    - ./utils/data.py
    - ./utils/engine.py
    - ./utils/visualisation.py
    - ./utils/utils.py
    - ./scripts/supervised_classification_wembedding.py
    - ./models/autoembedder_classification_model.py
    - ./models/base_classification_network.py
    outs:
    - ./data/plots_classification/
    - ./data/metrics_classification/