data_preprocessing:
    feature_handler_dir: ./feature_handling/
train_model:
    feature_handler_file: ./feature_handling/feature_handler.json
    manual_encoder_architecture: [] #empty list [] for automatic autencoder shape
    manual_decoder_architecture: [] #empty list [] for default symmetric autoencoder shape
    activation_function: ReLU
    test_data_fraction: 0.2
    embeddings_initializer: uniform
    optimizer: sgd
    loss: mse
    batch_size: 9
    epochs: 20
    learning_rate: 0.05
test_model:
    feature_handler_file: ./feature_handling/feature_handler.json
