data_preprocessing:
    feature_handler_dir: ./feature_handling/
    feature_action_file: ./feature_handling/feature_actions.json
train_autoembedder:
    output_directory: ./data/model
    feature_handler_file: ./feature_handling/feature_handler.json
    manual_encoder_architecture: [8,6,4] #empty list [] for automatic autencoder shape
    manual_decoder_architecture: [] #empty list [] for default symmetric autoencoder shape
    hidden_layer_activation_function: ReLU
    output_layer_activation_function: tanh
    test_data_fraction: 0.2
    embeddings_initializer: uniform
    normalisation_method: manual
    optimizer: adam
    loss: mse
    learning_rate: 0.005
    batch_size: 64
    epochs: 100
train_simple_classification_model:
    feature_handler_file: ./feature_handling/feature_handler.json
    activation_function: ReLU
    normalisation_method: manual
    test_data_fraction: 0.2
    embeddings_initializer: uniform
    optimizer: adam
    loss: cce
    learning_rate: 0.1
    metrics:
    - accuracy
    # - precision
    batch_size: 32
    epochs: 100