data_preprocessing:
    feature_handler_dir: ./feature_handling/
    feature_action_file: ./feature_handling/feature_actions.json
train_model:
    feature_handler_file: ./feature_handling/feature_handler.json

    manual_encoder_architecture: [] #empty list [] for automatic autencoder shape
    manual_decoder_architecture: [] #empty list [] for default symmetric autoencoder shape
    activation_function: ReLU
    test_data_fraction: 0.1
    embeddings_initializer: uniform
    optimizer: adam
    loss: mse
    batch_size: 9
    epochs: 10
    learning_rate: 0.05
test_model:
    feature_handler_file: ./feature_handling/feature_handler.json
    batch_size: 9
