data_preprocessing:
    feature_handler_dir: ./feature_handling/
train_model:
    feature_handler_file: ./feature_handling/feature_handler.json
    optimizer: sgd
    loss: mse
    batch_size: 32
    epochs: 20
    learning_rate: 0.01
