name: autoembedder_cml
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.4'
      - name: Run DVC Pipeline
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          python --version
          # Install requirements
          pip install -r requirements.txt
          pip install -e .

          #run pipeline
          dvc repro

          # Report metrics
          echo "## Metrics and Visualisation" >> report.md
          echo "### Autoembedding Training" >> report.md
          cat ./data/metrics_autoembedder/*.txt >> report.md
          cml publish ./data/plots_autoembedder/train_autoembedder_penguins_loss.pdf >> report.md

          echo "### Classification" >> report.md
          cat ./data/metrics_classification/*.txt >> report.md
          cml publish ./data/plots_classification/embedded_penguins_classification_loss.pdf >> report.md
          cml publish ./data/plots_classification/autoembedded_penguins_classification_loss.pdf >> report.md

          cml-send-comment report.md