name: autoembedder_cml
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      - name: Run DVC Pipeline
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          # Install requirements
          pip install -r requirements.txt

          #run pipeline
          dvc repro

          # Report metrics
          # echo "## Metrics" >> report.md

          # # Publish confusion matrix diff
          # echo "## Plots" >> report.md
          # echo "### Class confusions" >> report.md

          # # Publish regularization function diff
          # echo "### Effects of regularization" >> report.md

          # cml-send-comment report.md