name: autoembedder_cml
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      - name: Run DVC Pipeline
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          # Install requirements
          pip install -r requirements.txt

          #run pipeline
          dvc repro

          # Report metrics
          echo "## Metrics and Visualisation" >> report.md
          echo "### Autoembedding Training" >> report.md
          cat ./data/metrics_autoembedder/*.txt >> report.md
          cml publish ./data/plots_autoembedder/* >> report.md

          echo "### Classification" >> report.md
          cat ./data/metrics_classification/*.txt >> report.md
          cml publish ./data/plots_classification/* >> report.md

          cml-send-comment report.md